fix: downgrade eslint required version to allow using without issue
TypeError: this.libOptions.parse is not a function
https://youtrack.jetbrains.com/issue/WEB-57089/ESLint8.23-TypeError-this.libOptions.parse-is-not-a-function